### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by delusioninabox** [delusioninabox/praise-bot#29]
## Features
- [ ] Login with Slack
  - [ ] Takes to admin view of team settings
  - [ ] Add/remove values
  - [ ] Add/remove emojis
  - [ ] Enable/disable features
- [ ] Add to Slack button
